/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia_olimpo_p2_prc4.formularios;

/**
 *
 * @author jarvi
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        quedesea = new javax.swing.JLabel();
        logoinicio = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JPanel();
        Configurar = new javax.swing.JLabel();
        btnHacerVenta = new javax.swing.JPanel();
        HacerVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        bg.setBackground(java.awt.Color.white);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("Montserrat", 1, 60)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(51, 51, 255));
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("Bienvenido");
        bg.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 70));

        quedesea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        quedesea.setForeground(new java.awt.Color(153, 153, 153));
        quedesea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quedesea.setText("¿Qué desea hacer? Seleccione una opción");
        bg.add(quedesea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 350, -1));

        logoinicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia_olimpo_p2_prc4/recursosGraficos/logo inicio .png"))); // NOI18N
        bg.add(logoinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 470, 350));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia_olimpo_p2_prc4/recursosGraficos/Fondo 1 .png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 450));
        bg.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1090, 60));

        btnConfiguracion.setBackground(new java.awt.Color(51, 102, 255));
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseClicked(evt);
            }
        });

        Configurar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Configurar.setForeground(new java.awt.Color(255, 255, 255));
        Configurar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Configurar.setText("Configuración");

        javax.swing.GroupLayout btnConfiguracionLayout = new javax.swing.GroupLayout(btnConfiguracion);
        btnConfiguracion.setLayout(btnConfiguracionLayout);
        btnConfiguracionLayout.setHorizontalGroup(
            btnConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Configurar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnConfiguracionLayout.setVerticalGroup(
            btnConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfiguracionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Configurar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 150, 50));

        btnHacerVenta.setBackground(new java.awt.Color(51, 102, 255));

        HacerVenta.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        HacerVenta.setForeground(new java.awt.Color(255, 255, 255));
        HacerVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HacerVenta.setText("Hacer Venta");

        javax.swing.GroupLayout btnHacerVentaLayout = new javax.swing.GroupLayout(btnHacerVenta);
        btnHacerVenta.setLayout(btnHacerVentaLayout);
        btnHacerVentaLayout.setHorizontalGroup(
            btnHacerVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHacerVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HacerVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnHacerVentaLayout.setVerticalGroup(
            btnHacerVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHacerVentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HacerVenta)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(btnHacerVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //BOTON SIGUIENTE JFRAME
    private void btnConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseClicked
        
        //Invocamos a la ventana 
        frmConfiguracion newframe = new frmConfiguracion();
        newframe.setVisible(true);
        this.dispose();
        
        
          
      
    }//GEN-LAST:event_btnConfiguracionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Configurar;
    private javax.swing.JLabel HacerVenta;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPanel btnConfiguracion;
    private javax.swing.JPanel btnHacerVenta;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel logoinicio;
    private javax.swing.JLabel quedesea;
    // End of variables declaration//GEN-END:variables
}
