/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia_olimpo_p2_prc4.formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author jarvi
 */
public class frmVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmVentas
     */
    public frmVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JPanel();
        Regresar = new javax.swing.JLabel();
        lblBuscartxt = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        spBuscar = new javax.swing.JSeparator();
        lblHazVenta = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        spNombreProducto = new javax.swing.JSeparator();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        spStock = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        spPrecio = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimientoEmpleados = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        spTotal = new javax.swing.JSeparator();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        spCantidad = new javax.swing.JSeparator();
        btnRegresar1 = new javax.swing.JPanel();
        Regresar1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(0, 102, 255));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        Regresar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regresar.setText("Hacer Venta");
        Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Regresar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 320, 310, 50));

        lblBuscartxt.setBackground(new java.awt.Color(102, 102, 102));
        lblBuscartxt.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblBuscartxt.setForeground(new java.awt.Color(102, 102, 102));
        lblBuscartxt.setText("Buscar");
        bg.add(lblBuscartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, -1));

        txtBuscar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        bg.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, 30));
        bg.add(spBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 10));

        lblHazVenta.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblHazVenta.setForeground(new java.awt.Color(0, 0, 153));
        lblHazVenta.setText("Haz una venta");
        bg.add(lblHazVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 860, 90));

        lblNombreProducto.setBackground(new java.awt.Color(102, 102, 102));
        lblNombreProducto.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreProducto.setText("Nombre del Producto");
        bg.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, -1));

        txtNombreProducto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProducto.setBorder(null);
        txtNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProductoMousePressed(evt);
            }
        });
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        bg.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 30));
        bg.add(spNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 320, 10));

        lblStock.setBackground(new java.awt.Color(102, 102, 102));
        lblStock.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblStock.setForeground(new java.awt.Color(102, 102, 102));
        lblStock.setText(" Stock");
        bg.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, -1));

        txtStock.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtStock.setForeground(new java.awt.Color(153, 153, 153));
        txtStock.setBorder(null);
        txtStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtStockMousePressed(evt);
            }
        });
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        bg.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 310, 30));
        bg.add(spStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 320, 10));

        lblPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblPrecio.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(102, 102, 102));
        lblPrecio.setText("Precio");
        bg.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 200, -1));

        txtPrecio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecio.setBorder(null);
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMousePressed(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        bg.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 310, 30));
        bg.add(spPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 320, 10));

        tblMantenimientoEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        tblMantenimientoEmpleados.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tblMantenimientoEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMantenimientoEmpleados.setGridColor(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(tblMantenimientoEmpleados);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 1080, 350));

        lblTotal.setBackground(new java.awt.Color(102, 102, 102));
        lblTotal.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setText("Total");
        bg.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 200, -1));

        txtTotal.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(153, 153, 153));
        txtTotal.setBorder(null);
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTotalMousePressed(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        bg.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 310, 30));
        bg.add(spTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 320, 10));

        lblCantidad.setBackground(new java.awt.Color(102, 102, 102));
        lblCantidad.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(102, 102, 102));
        lblCantidad.setText("Cantidad ");
        bg.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 200, -1));

        txtCantidad.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setBorder(null);
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCantidadMousePressed(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        bg.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 310, 30));
        bg.add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 320, 10));

        btnRegresar1.setBackground(new java.awt.Color(0, 102, 255));
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseClicked(evt);
            }
        });

        Regresar1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Regresar1.setForeground(new java.awt.Color(255, 255, 255));
        Regresar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regresar1.setText("<   Regresar");
        Regresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegresar1Layout = new javax.swing.GroupLayout(btnRegresar1);
        btnRegresar1.setLayout(btnRegresar1Layout);
        btnRegresar1Layout.setHorizontalGroup(
            btnRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresar1Layout.createSequentialGroup()
                .addComponent(Regresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnRegresar1Layout.setVerticalGroup(
            btnRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Regresar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        lblLimpiar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setText("Limpiar");
        lblLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addComponent(lblLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));
        bg.add(lblTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        //Invocamos a la ventana Inicio
        
    }//GEN-LAST:event_RegresarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        Calcular(1);
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed

    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtNombreProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMousePressed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStockMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMousePressed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMousePressed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtTotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMousePressed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtCantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMousePressed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void Regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar1MouseClicked
      frmInicio newframe = new frmInicio();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Regresar1MouseClicked

    private void btnRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseClicked
        frmInicio newframe = new frmInicio();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1MouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        txtBuscar.setText("");
        txtNombreProducto.setText("");
        txtStock.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
        txtNombreProducto.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtTotal.setText("");
        txtBuscar.setText("");
    }//GEN-LAST:event_lblLimpiarMouseClicked

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
       
       
    }//GEN-LAST:event_txtCantidadKeyPressed

    
        public void Calcular(int opciones){
        double resultado=0;
        try {
            double num1 = Double.parseDouble(txtCantidad.getText());
            double num2 = Double.parseDouble(txtPrecio.getText());
            switch(opciones){
                case 1: resultado=num1*num2;break; 
            }
            lblTotalPagar.setText("" + resultado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe digitar solo valores numericos.\n Intentelo de nuevo");

        }
        catch(Exception e ){
            String msj = "Ups! Algo salio mal intentalo de nuevo "+e;
            JOptionPane.showMessageDialog(null, msj);
        }
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Regresar1;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnRegresar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscartxt;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblHazVenta;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JSeparator spBuscar;
    private javax.swing.JSeparator spCantidad;
    private javax.swing.JSeparator spNombreProducto;
    private javax.swing.JSeparator spPrecio;
    private javax.swing.JSeparator spStock;
    private javax.swing.JSeparator spTotal;
    private javax.swing.JTable tblMantenimientoEmpleados;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
